### ISSUE TITLE
Adjust memory available to shm

### ISSUE THREAD

**Issue by drpebcak** [timescale/timescaledb-kubernetes#127]
Currently there is no direct way to accomplish this, but if the chart supported mounting tmpfs to /dev/shm it could resolve some issues.

**Comment by feikesteenbergen** [comment]
By default, PostgreSQL should only be using `/dev/shm` for parallel workers requiring `work_mem`, see this [mailing list exchange](https://www.postgresql.org/message-id/flat/7E4D7DA4-E093-4F6A-AE8E-81A73B995A8D%40gmail.com).

I'm not against this, but I think we should make it disabled by default and point to this documentation as to why this is needed.

This seems to describe exactly what's needed:

https://docs.okd.io/latest/dev_guide/shared_memory.html

The major downside currently is that instead of 1 session getting an 

```console
53100 | ERROR:  could not resize shared memory segment "/PostgreSQL.12345" to 4194304 bytes: No space left on device
```
The whole pod [would be rescheduled](https://github.com/kubernetes/kubernetes/issues/28272#issuecomment-549223540) - which seems a bit too much.

So, this is a huge foot gun.

Related issues:

- https://github.com/kubernetes/kubernetes/pull/63641
- https://github.com/kubernetes/kubernetes/pull/34928

**Comment by drpebcak** [comment]
I agree about it being disabled by default - I just ran into a situation where I needed it, and I had to manually edit the statefulset to get it.

**Comment by feikesteenbergen** [comment]
@drpebcak just created a PR to include this - but I'd be happy for any feedback about the interface as well as the documentation.

**Comment by feikesteenbergen** [comment]
https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.5.5
