### ISSUE TITLE
Requested WAL segment has already been removed (?)

### ISSUE THREAD

**Issue by MrRexZ** [timescale/timescaledb-kubernetes#138]
So in my master timescale instance, I'm getting the following errors:
```
timescaledb /var/run/postgresql:5432 - rejecting connections                                                                                                                                                                               │
│ timescaledb 2020-03-28 19:45:04 UTC [3155]: [5e7fa940.c53-1] [unknown]@[unknown],app=[unknown] [00000] LOG:  connection received: host=[local]                                                                                             │
│ timescaledb 2020-03-28 19:45:04 UTC [3155]: [5e7fa940.c53-2] postgres@postgres,app=[unknown] [57P03] FATAL:  the database system is starting up                                                                                            │
│ timescaledb 2020-03-28 19:45:04 UTC [3156]: [5e7fa940.c54-1] [unknown]@[unknown],app=[unknown] [00000] LOG:  connection received: host=[local]                                                                                             │
│ timescaledb 2020-03-28 19:45:04 UTC [3156]: [5e7fa940.c54-2] postgres@postgres,app=[unknown] [57P03] FATAL:  the database system is starting up                                                                                            │
│ timescaledb 2020-03-28 19:45:04,856 WARNING: Retry got exception: 'connection problems'                                                                                                                                                    │
│ timescaledb 2020-03-28 19:45:05 UTC [3165]: [5e7fa941.c5d-1] @,app= [00000] LOG:  started streaming WAL from primary at 1/20000000 on timeline 3                                                                                           │
│ timescaledb 2020-03-28 19:45:05 UTC [3165]: [5e7fa941.c5d-2] @,app= [XX000] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000030000000100000020 has already been removed                                │
│ 
```
Now looking at the last line, it's saying it couldn't find the WAL segment. I went to inside the pods (the master & worker instance) to inspect, and indeed there's no such WAL file
I then realized that backup is disabled, by [default according to this doc](https://github.com/timescale/timescaledb-kubernetes/blob/a0b6ef1904035b206367dcaa2e325ab1ba62cf60/charts/timescaledb-single/admin-guide.md).

Looking into the source code and I found [these](https://github.com/timescale/timescaledb-kubernetes/blob/84f43218735b26c532835c2fbe139110e70c7e17/charts/timescaledb-single/templates/configmap-scripts.yaml#L23) :
```
  # If no backup is configured, archive_command would normally fail. A failing archive_command on a cluster
  # is going to cause WAL to be kept around forever, meaning we'll fill up Volumes we have quite quickly.
  #
  # Therefore, if the backup is disabled, we always return exitcode 0 when archiving
```

And connecting all those dots together, if I understand correctly, this means that by default, timescale will delete WAL file (due to the exit code 0), even with no backup provided.
Doesn't this mean Timescale can potentially create a corrupted database state (if used without backing up WAL files), as what I'm seeing in the first snippet above?
If so, I think maybe we should enable backup by default, or have the option to disable the use of WAL for recovery (if that's possible).

EDIT:
Oh apparently there's already `basebackup` as default : https://github.com/timescale/timescaledb-kubernetes/blob/286b1fb9239679060ea8b6caf06b5016c01cea66/charts/timescaledb-single/values.yaml#L179
Now this makes it weird that I was getting the WAL segment unfound error, given I haven't modified the WAL and WAL archives files before..

**Comment by MrRexZ** [comment]
Oh apparently there's `basebackup` already implemented as the default.
So this makes it weird I'm getting the WAL segment unfound error in the first place, given I haven't hand-played around the WAL & WAL archives files...

**Comment by feikesteenbergen** [comment]
The answer to this problem requires some details, as there's quite a few things to unpack here.

> Doesn't this mean Timescale can potentially create a corrupted database state (if used without backing up WAL files), as what I'm seeing in the first snippet above?

No.

There is no corrupted database state in the problem you describe, there is however the following problem:

- The primary has advanced more than the replica kan keep up with.

Without going into too much detail, WAL is a perpetual stream of changes generated by the primary.
The WAL Volume however is of limited size, therefore WAL needs to be removed at some point.

To allow replica's to follow the primary a few things will prevent WAL from being deleted:

- Usage of replication slots; a replication slot basically points at a position in the WAL stream.
    If the replication slot is not advanced, the WAL is not removed
- `wal_keep_segments`, by setting this value higher, you enforce the primary to keep more WAL.
- `max_wal_size` by choosing a higher `max_wal_size` you make it more likely WAL will not quickly be removed.

> this means that by default, timescale will delete WAL file (due to the exit code 0), even with no backup provided.

Yes, without a backup method, we do not have any option other than to remove WAL files, otherwise the database
would have to stop once the WAL Volume is filled with WAL. I would therefore advise everyone to enable the backup.

> or have the option to disable the use of WAL for recovery (if that's possible).

WAL is the foundation of replication in PostgreSQL, so therefore it cannot be disabled.

> If so, I think maybe we should enable backup by default

We can not easily enable it by default. These Helm Charts allow you to run TimescaleDB on every Kubernetes cluster.
However, the backup requires an s3-compatible object storage to be available to the user.

> Oh apparently there's already basebackup as default :
> Line 179 in 286b1fb
>    - basebackup 

This value describes the bootstrap method, not the backup method.

The [bootstrap](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap) method of Patroni defines
how a replica is created. By default Patroni will use `pg_basebackup` to create a replica if no backup method is available.

> 000000030000000100000020 has already been removed

I cannot fully understand your situation, however this does tell me a few things:

- you have had 2 failovers in your deployment (first part of the filename is `00000003`, so you're on timeline 3)
- You have not had a lot of changes yet in your deployment (`0000000100000020`), you've only burned through 20 WAL files.

I'm guessing that you've had 2 failovers in quick succession; if the requested WAL segment cannot be found and no backup
is available, the solution would be for the failing replica, is to clean out the Data and Wal Volume.

If a backup would have been available, this WAL segment would have been able to be fetched from the archives.
