### ISSUE TITLE
[ISSUE] Most recent charts not published on charts.timescale.com

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/timescaledb-kubernetes#324]
**Describe the bug**
The charts available in `charts.timescale.com` have version 0.8.2, in this repo the most recent version is 0.10.0.

**To Reproduce**
```
helm repo add timescale 'https://charts.timescale.com'
helm repo update
helm show chart timescale/timescaledb-single
```
Output:
```
apiVersion: v1
description: TimescaleDB HA Deployment.
home: https://github.com/timescale/timescaledb-kubernetes
maintainers:
- email: support@timescale.com
  name: TimescaleDB
name: timescaledb-single
sources:
- https://github.com/timescale/timescaledb-kubernetes
- https://github.com/timescale/timescaledb-docker-ha
- https://github.com/zalando/patroni
version: 0.8.2
```
**Expected behavior**
I expect 0.10.0 to be available.

**Comment by peedrr** [comment]
I just spoke with @feikesteenbergen on Slack, who confirmed that the timescale.com-hosted repo should indeed be the primary resource. (Rather than the github repo which is instructed in the [main README doc](https://github.com/timescale/timescaledb-kubernetes#repository) :/ )

I agree it would help adoption if it was up to date, and also wasn't showing signs of errors, as per #328

**Comment by JamesGuthrie** [comment]
It looks like this issue has been fixed.
